'use strict';
// MOCK TESTS ONLY: real app.js / ai-client.js run in a stubbed browser; the LLM provider is mocked. No real provider is called.
const vm = require('vm'), fs = require('fs'), path = require('path'), assert = require('assert');
const R = path.join(__dirname, '..'), rd = (f) => fs.readFileSync(path.join(R, f), 'utf8');
let pass = 0, fail = 0; const q = [];
const t = (name, fn) => q.push([name, fn]);
function boot(opts = {}) {
  const store = opts.store || {}, els = {}, el = () => ({ innerHTML: '', value: '', textContent: '', dataset: {}, focus() {}, style: {}, readOnly: false });
  const ctx = { document: { querySelector: (s) => els[s] || (els[s] = el()), addEventListener() {} }, localStorage: { getItem: (k) => (k in store ? store[k] : null), setItem: (k, v) => { store[k] = String(v); }, removeItem: (k) => { delete store[k]; } }, navigator: { language: 'en-US' }, console: { log() {}, error() {} }, setTimeout: () => 0, clearTimeout() {}, setInterval: () => 0, confirm: () => true, AbortController, Promise, fetch: opts.fetch || (() => Promise.reject(new Error('no net'))) };
  ctx.window = ctx; vm.createContext(ctx);
  vm.runInContext(rd('app.js'), ctx, { filename: 'app.js' });
  if (opts.client) vm.runInContext(rd('ai-client.js'), ctx, { filename: 'ai-client.js' });
  ctx.$ev = (e) => vm.runInContext(e, ctx); ctx.store = store; return ctx;
}
const MEAL = { name: 'MealMind', pitch: 'MealMind is an AI-powered platform that helps restaurants reduce food waste by predicting demand and recommending how much food to prepare. We help restaurants reduce unnecessary food preparation, protect margins, and make better daily inventory decisions.', customer: 'Independent restaurants and small restaurant chains', price: '₹2999/month', trac: '12 pilot restaurants, 3 paying customers, 18% average reduction in food waste during pilot testing', unk: [] };
const MKT = 'We are using a bottom-up market estimate rather than a broad industry TAM. For our initial target geography, we estimate about 50,000 independent restaurants and small-chain locations that fit our customer profile. At an average price of ₹3,000 per month, that gives us a serviceable revenue pool of roughly ₹180 crore in annual recurring revenue if we reached all of them. Our first milestone is 1,000 locations, which would represent about ₹36 crore ARR. The 50,000-location estimate is an assumption we still need to validate through restaurant directories and POS partners.';
const GEN = 'We interviewed 40 owners; 3 pay ₹2999 per month, 12 run pilots with 18% less food waste, and 2 renewed after 60 days. Our market is restaurants and our competitor Wasteless lacks POS integration. CAC is ₹2,400, margin 71%, payback under 3 months. I built the model and my cofounder ran ops for 6 years; we ship weekly.';
const AMB = 'Free copies will not hurt: we integrate with each restaurant POS and hold their live data so switching costs are high; our pilots renew and we ship weekly.';
const BOSS = 'MealMind cuts restaurant food waste by predicting daily demand. We interviewed 40 owners, 3 pay ₹2999 per month. Our moat is POS integration and live data. CAC is ₹2,400 with 71% margin. Competitors and churn are covered by renewals; we raise ₹50 lakh.';
function finishSim(c, first) { let g = 0; c.$ev('startWar()'); while (c.$ev('S.stage') !== 'done' && g++ < 30) { const st = c.$ev('S.stage'); const txt = st === 'ambush' ? AMB : st === 'boss' ? BOSS : (first && c.$ev('S.answers.length') === 0 ? first : GEN); assert(c.submitInput({ mode: 'text', text: txt }), 'submit failed at ' + st); } assert.strictEqual(c.$ev('S.stage'), 'done'); }
const user = (c, open) => { c.$ev(`OPEN=${open ? JSON.stringify(open) : 'null'}`); c.$ev(`newSim(${JSON.stringify(MEAL)},false)`); };
const bad = /(?<![\d,])999(?!\d)/;

t('landing shows brand, tagline, CTAs', () => { const c = boot(), h = c.$ev('V.dash()'); for (const s of ['INVESTOR WAR', 'AI SHARK TANK SIMULATOR', 'YOUR STARTUP HAS 10 MINUTES TO SURVIVE.', 'Five AI investors. Zero politeness. One investment decision.', 'ENTER THE WAR', 'TRY LIVE DEMO']) assert(h.includes(s), s); });
t('SHARK VISUAL renders in hero + header + five investor marks', () => { const c = boot(), h = c.$ev('V.dash()'); assert(/<svg class="shark"[^>]*aria-label/.test(h) && /<path /.test(h)); assert(rd('index.html').includes('<svg') && rd('index.html').includes('AI SHARK TANK SIMULATOR')); assert.strictEqual((h.match(/class="p5i"/g) || []).length, 5); assert(!/https?:\/\/[^"' ]+\.(png|jpe?g|gif|webp)/i.test(rd('app.js') + rd('index.html')), 'no external images'); });
t('five investors + profiles', () => { const c = boot(), h = c.$ev('V.inv()'); for (const n of ['MARKET SHARK', 'CUSTOMER SHARK', 'MONEY SHARK', 'EXECUTION SHARK', 'THE DEVIL']) assert(h.includes(n)); assert.strictEqual((h.match(/VIEW PROFILE/g) || []).length, 5); for (const k of ['market', 'customer', 'money', 'exec', 'devil']) { const p = c.$ev(`profH('${k}')`); for (const s of ['CONFIDENCE', 'EVIDENCE STRENGTH', 'RISK LEVEL', 'CURRENT CONCERN', 'START INVESTOR WAR']) assert(p.includes(s), k + s); } });
t('REGRESSION ₹2999: market answer graded on its own merits, no stale text, no ₹999 anywhere', () => {
  const c = boot(); user(c, 'market'); c.$ev('startWar()'); assert.strictEqual(c.$ev('S.cur.inv'), 'market', 'chosen investor opens the war');
  assert(c.submitInput({ mode: 'text', text: MKT }));
  const a = c.$ev('S.answers[0]'); assert.strictEqual(a.inv, 'market'); assert(['strong', 'verified'].includes(a.g), 'grade ' + a.g); assert.notStrictEqual(a.g, 'verified', 'estimate must not be VERIFIED');
  assert.strictEqual(c.$ev('S.con.length'), 0, 'no fabricated contradiction from "small-chain"');
  assert(!/Vague|hedged|self-defeating/.test(c.$ev('S.why.market')));
  finishSim(c, null);
});
t('REGRESSION ₹2999: full run, verdict/lab/xray/history contain no ₹999, reflect ₹2999', () => {
  const c = boot(); user(c, 'market'); c.$ev('startWar()'); c.submitInput({ mode: 'text', text: MKT }); let g = 0; while (c.$ev('S.stage') !== 'done' && g++ < 30) { const st = c.$ev('S.stage'); c.submitInput({ mode: 'text', text: st === 'ambush' ? AMB : st === 'boss' ? BOSS : GEN }); }
  assert.strictEqual(c.$ev('S.stage'), 'done'); const all = ['V.ver()', 'V.lab()', 'V.xray()', 'V.radar()', 'V.evid()', 'V.split()', 'V.dash()', 'V.hist()'].map((e) => c.$ev(e)).join('\n');
  assert(!bad.test(all), 'stale 999 found'); assert(all.includes('₹2999'), 'current price missing'); assert(!/Vague, hedged/.test(c.$ev('V.ver()')) || c.$ev('S.answers.some(a=>a.g==="weak")'));
  const v = c.$ev('S.verdict'); assert(['INVEST', 'INVEST WITH CONDITIONS', 'INTERESTED — PROVE IT', 'PASS'].includes(v.o)); assert.strictEqual(c.$ev('S.prob'), v.p);
  const vh = c.$ev('V.ver()'); for (const s of ['STRONGEST ADVANTAGE', 'BIGGEST RED FLAG', 'FOUNDER BLIND SPOT', 'HIDDEN ASSUMPTIONS', 'UNSUPPORTED CLAIMS', 'EVIDENCE NEEDED', 'BIGGEST WEAKNESS', 'TOP OBJECTIONS', 'RECOMMENDED NEXT STEPS', 'Founder readiness', 'Market potential']) assert(vh.includes(s), s);
  const lab = c.$ev('V.lab()'); for (const s of ['VALIDATION LAB', 'SUCCESS CRITERIA', 'PITCH REWRITER', '7-DAY FOUNDER PLAN', 'Day 7']) assert(lab.includes(s), s);
});
t('simulationId: new/restart/refresh/demo/user isolation', () => {
  const c = boot(); c.$ev('newSim(DEMO,true)'); const d = c.$ev('S.sid'); assert(c.$ev('S.ns') === 'demo' && /₹999/.test(c.$ev('S.st.price')));
  assert(!c.store['iw:v3:active'] && c.store['iw:v3:demo'], 'demo must not be stored as active'); c.$ev('S=null;restore()'); assert.strictEqual(c.$ev('S'), null, 'refresh after demo must not restore demo as a user sim');
  user(c); const u = c.$ev('S.sid'); assert.notStrictEqual(u, d); assert(c.$ev('S.ns') === 'user' && c.$ev('S.st.price') === '₹2999/month'); assert(!bad.test(JSON.stringify(c.$ev('S'))), 'demo leaked into user sim');
  c.$ev('S=null;restore()'); assert.strictEqual(c.$ev('S.sid'), u, 'refresh restores active user sim'); c.$ev('newSim(DEMO,true)'); assert(!/2999/.test(JSON.stringify(c.$ev('S'))), 'user leaked into demo');
  c.$ev('S=null;restore()'); assert.strictEqual(c.$ev('S.sid'), u, 'user sim survives a demo run'); user(c); assert.notStrictEqual(c.$ev('S.sid'), u, 'new sim = new id');
  assert(!c.store['iw_s'], 'legacy key removed');
});
t('restart resets memory/confidence/probability', () => { const c = boot(); user(c, 'market'); c.$ev('startWar()'); c.submitInput({ mode: 'text', text: MKT }); const p1 = c.$ev('S.prob'); user(c, 'market'); assert.strictEqual(c.$ev('S.answers.length'), 0); assert.strictEqual(c.$ev('S.conf.market'), c.$ev('BASE.conf.market') - 0); assert.notStrictEqual(p1, undefined); assert.strictEqual(c.$ev('S.claims.filter(x=>x.src!=="Intake").length'), 0); });
t('history stays separate from active state', () => { const c = boot(); user(c, 'market'); finishSim(c); const sid = c.$ev('S.sid'), h = JSON.parse(c.store['iw:v3:history']); assert(h.some((x) => x.sid === sid && x.ns === 'user')); const before = c.$ev('S.sid'); c.$ev('newSim(DEMO,true)'); assert.notStrictEqual(c.$ev('S.sid'), before); c.$ev('S=null;restore()'); assert.strictEqual(c.$ev('S'), null, 'a completed run is never restored: it lives in history only'); assert(c.$ev('V.hist()').includes('Attempt 1')); });
t('BOSS scoring keys canonical everywhere + objection handling shown', () => {
  const c = boot(), B = c.$ev('BOSS'); const J=JSON.stringify; assert.strictEqual(J(Object.keys(c.$ev('evalBoss("We interviewed 3 owners, price 100 per month, churn is low")').c)), J(B)); assert.strictEqual(J(B), J(require('../lib/ai-service').BOSS_CRITERIA));
  const sys = rd('lib/ai-service.js'); for (const k of B) assert(sys.includes(k), k); assert(!/Addresses objections|Persuasiveness/.test(rd('app.js') + rd('ai-client.js') + sys));
  const n = c.$ev('normBoss([{name:"Addresses objections",score:70},{name:"Persuasiveness",score:90},{name:"Clarity",score:55}],evalBoss("x y z").c)'); assert.strictEqual(JSON.stringify(Object.keys(n).sort()), JSON.stringify(B.slice().sort())); assert.strictEqual(n['Objection handling'], 70); assert.strictEqual(n.Clarity, 55);
  user(c); finishSim(c); assert(c.$ev('V.ver()').includes('Objection handling'));
});
t('server judge maps provider aliases to canonical boss keys (MOCK)', async () => { process.env.LLM_API_KEY = 'x'; const s = require('../lib/ai-service'); global.fetch = async () => ({ ok: true, json: async () => ({ content: [{ text: JSON.stringify({ score: 70, note: 'n', criteria: [{ name: 'Addresses objections', score: 60 }, { name: 'Clarity', score: 80 }] }) }] }) }); const r = await s.handle({ action: 'judge', kind: 'boss', text: 'hi there', state: {} }); assert.deepStrictEqual(r.criteria.map((x) => x.name), ['Objection handling', 'Clarity']); delete process.env.LLM_API_KEY; });
t('text vs voice: identical text => identical evaluation', () => { const a = boot(), b = boot(); for (const [c, m] of [[a, 'text'], [b, 'voice']]) { user(c, 'market'); c.$ev('startWar()'); c.submitInput({ mode: m, text: MKT }); } assert.strictEqual(a.$ev('S.answers[0].g'), b.$ev('S.answers[0].g')); assert.strictEqual(a.$ev('S.prob'), b.$ev('S.prob')); assert.strictEqual(b.$ev('S.answers[0].mode'), 'voice'); assert.strictEqual(JSON.stringify(a.$ev('normalizeFounderInput({mode:"voice",text:"  a \\n b "})')), JSON.stringify({ mode: 'voice', text: 'a b' })); });
t('empty / weak / strong / I don\'t know', () => { const c = boot(); user(c, 'market'); c.$ev('startWar()'); assert.strictEqual(c.submitInput({ mode: 'text', text: '   ' }), false); c.submitInput({ mode: 'text', text: "I don't know" }); assert.strictEqual(c.$ev('S.answers[0].g'), 'avoiding'); c.submitInput({ mode: 'text', text: 'We think the market is probably huge, hopefully.' }); assert(['weak', 'unsupported'].includes(c.$ev('S.answers[1].g'))); });
t('contradiction radar + devil priority + investor switch (no fixed rotation)', () => { const c = boot(); user(c, 'market'); c.$ev('startWar()'); c.submitInput({ mode: 'text', text: 'Our real target is large restaurant chains and enterprise kitchens at ₹4,999 per month with 8 pilots.' }); assert(c.$ev('S.con.length') >= 1); assert.strictEqual(c.$ev('S.cur.inv'), 'devil'); assert(c.$ev('V.radar()').includes('CONTRADICTION DETECTED')); assert(c.$ev('V.war()').includes('INVESTOR SWITCH')); const seq = []; const c2 = boot(); user(c2, 'market'); c2.$ev('startWar()'); for (let i = 0; i < 4; i++) { seq.push(c2.$ev('S.cur.inv')); c2.submitInput({ mode: 'text', text: i % 2 ? GEN : 'We think customers will like it.' }); } assert.notDeepStrictEqual(seq, ['market', 'customer', 'money', 'exec']); });
t('assumption x-ray / evidence meter / memory / probability move', () => { const c = boot(); user(c, 'market'); const p0 = c.$ev('S.prob'); c.$ev('startWar()'); c.submitInput({ mode: 'text', text: MKT }); assert(c.$ev('V.xray()').includes('ASSUMPTION')); assert(c.$ev('V.evid()').includes('EVIDENCE METER')); assert(c.$ev('V.split()').includes('INVESTOR MEMORY') && c.$ev('V.split()').includes('3 paying')); assert.notStrictEqual(c.$ev('S.prob'), p0); });
t('"I DON\'T KNOW YET" becomes investigation target, nothing invented', () => { const c = boot(); c.$ev(`OPEN=null;newSim(${JSON.stringify({ name: 'X', pitch: 'A tool for dentists to book patients faster.', customer: '', price: '', trac: '', comp: '', unk: ['customer', 'price', 'traction', 'competition'] })},false)`); assert(c.$ev('V.war()').includes('investigation targets')); assert.strictEqual(c.$ev('S.claims.some(x=>x.type==="price")'), false); c.$ev('startWar()'); assert(!/999/.test(JSON.stringify(c.$ev('S')))); });
t('ambush + final boss + demo run end-to-end on the same engine', () => { const c = boot(); c.$ev('newSim(DEMO,true)'); c.$ev('startWar()'); let g = 0; const DA = c.$ev('DA'); while (c.$ev('S.stage') !== 'done' && g++ < 30) { const st = c.$ev('S.stage'); c.submitInput({ mode: 'text', text: st === 'ambush' ? DA.amb : st === 'boss' ? DA.boss : DA[c.$ev('S.cur.inv')][Math.min(c.$ev('S.asked[S.cur.inv]'), 2) - 0] || DA.devil[0] }); } assert.strictEqual(c.$ev('S.stage'), 'done'); assert(c.$ev('S.ambush.score') >= 0 && Object.keys(c.$ev('S.boss.c')).length === 7); assert(c.$ev('S.con.length') >= 1); });
t('voice: unsupported, denied, empty, cancel, review-before-send', () => { const c = boot(); user(c, 'market'); c.$ev('startWar()'); c.$ev("startRec('ans')"); assert(c.$ev('VC.phase') === 'err' && /not supported/.test(c.$ev('VC.msg')));
  const mk = (fn) => { c.SpeechRecognition = class { start() { fn(this); } abort() {} stop() {} }; }; c.$ev('voiceReset()');
  mk((r) => { r.onstart(); r.onerror({ error: 'not-allowed' }); r.onend(); }); c.$ev("startRec('ans')"); assert(/denied/.test(c.$ev('VC.msg'))); c.$ev('voiceReset()');
  mk((r) => { r.onstart(); r.onend(); }); c.$ev("startRec('ans')"); assert(/No speech/.test(c.$ev('VC.notice'))); c.$ev('voiceReset()');
  mk((r) => { r.onstart(); r.onresult({ resultIndex: 0, results: [Object.assign([{ transcript: 'we have three paying customers' }], { isFinal: true })] }); r.onend(); }); c.$ev("startRec('ans')"); assert.strictEqual(c.$ev('VC.phase'), 'review'); assert.strictEqual(c.$ev('S.answers.length'), 0, 'never auto-submit'); assert(c.$ev("voiceH('ans')").includes('Transcript ready — review before sending')); c.$ev("VC.text='we have three paying customers today'");  c.$ev('vSubmit()'); assert.strictEqual(c.$ev('S.answers.length'), 1); assert.strictEqual(c.$ev('S.answers[0].mode'), 'voice');
  c.$ev('voiceReset()'); mk(() => {}); c.$ev("startRec('ans')"); c.$ev('cancelRec()'); assert(/cancelled/.test(c.$ev('VC.notice'))); });
t('AI failure falls back to DEMO MODE (MOCK)', async () => { const c = boot({ client: true }); c.$ev('AIC.live=true'); user(c); await c.$ev("aiCall('question',{}).catch(()=>0)"); await c.$ev("aiCall('question',{}).catch(()=>0)"); assert.strictEqual(c.$ev('AIC.live'), false); assert(/DEMO MODE/.test(els0(c))); });
const els0 = (c) => c.$ev("$('#aist').textContent+' '+$('#mode').textContent");
t('stale async AI result cannot write into a newer simulation (MOCK)', async () => { let release; const gate = new Promise((r) => { release = r; }); const c = boot({ client: true, fetch: async (u, o) => { await gate; return { ok: true, json: async () => ({ strongestAdvantage: 'OLD', redFlag: 'OLD', blindSpot: 'OLD', objections: [], evidenceNeeded: [], nextSteps: [], experiments: [{ hypothesis: 'OLD', experiment: 'OLD', target: 'x', success: 'x', metric: 'x', time: 'x', cost: 'x' }], pitch: { problem: 'OLD', customer: 'OLD', evidence: 'OLD', solution: 'OLD', differentiation: 'OLD', businessModel: 'OLD', traction: 'OLD', ask: 'OLD' } }) }; } }); c.$ev('AIC.live=true'); user(c); c.$ev('startWar()'); c.$ev("S.stage='boss';S.boss={avg:60,c:{}};S.ambush={score:50,rows:[],note:''}"); const p = c.$ev('finish()'); user(c); release(); await p; assert.strictEqual(c.$ev('S.verdict'), null); assert.strictEqual(c.$ev('S.aiExps'), undefined); assert(!JSON.stringify(c.$ev('S')).includes('OLD')); });
t('api/ai.js: size, rate-limit, method, no-key, no raw errors (MOCK)', async () => { delete process.env.LLM_API_KEY; const h = require('../api/ai.js'); const call = (req) => new Promise((res) => { const o = { code: 200, h: {}, setHeader(k, v) { this.h[k] = v; }, status(c) { this.code = c; return this; }, json(b) { res({ code: this.code, b }); } }; h(Object.assign({ method: 'POST', headers: { 'x-forwarded-for': 'a' } }, req), o); });
  assert.strictEqual((await call({ method: 'GET' })).code, 405); const r = await call({ body: '{"action":"question"}' }); assert.strictEqual(r.code, 503); assert.deepStrictEqual(r.b, { error: 'demo' }); assert.strictEqual((await call({ body: 'x'.repeat(70000) })).code, 413); assert.strictEqual((await call({ body: '{bad' })).code, 502);
  process.env.LLM_API_KEY = 'sk-secret'; global.fetch = async () => ({ ok: false, status: 500, text: async () => 'sk-secret stack trace' }); const e = await call({ body: '{"action":"verdict","state":{}}', headers: { 'x-forwarded-for': 'b' } }); assert(!JSON.stringify(e.b).includes('sk-secret') && e.code === 502);
  global.fetch = async () => ({ ok: true, json: async () => ({ content: [{ text: 'not json at all' }] }) }); assert.strictEqual((await call({ body: '{"action":"evaluate","state":{},"answer":"a"}', headers: { 'x-forwarded-for': 'c' } })).b.error, 'bad-json'); global.fetch = async () => ({ ok: true, json: async () => ({ content: [{ text: '{"grade":"banana"}' }] }) }); assert.strictEqual((await call({ body: '{"action":"evaluate","state":{}}', headers: { 'x-forwarded-for': 'd' } })).b.error, 'bad-shape');
  let last; for (let i = 0; i < 62; i++) last = await call({ body: '{"action":"status"}', headers: { 'x-forwarded-for': 'rl' } }); assert.strictEqual(last.code, 429); delete process.env.LLM_API_KEY; });

const poison = () => ({ 'iw:v3:active': JSON.stringify({ S: { sid: 'old', ns: 'user', stage: 'done', st: { name: 'MealMind', price: '₹999 per month' }, answers: new Array(8).fill({ q: 'q', a: 'a', inv: 'market', g: 'weak', cl: [] }), conf: { market: 40 }, risk: { market: 60 }, prob: 63, verdict: { p: 63, o: 'INVEST WITH CONDITIONS', dim: {} } }, view: 'ver' }), 'iw_s': JSON.stringify({ S: { st: { name: 'MealMind' }, stage: 'done', prob: 63 }, view: 'ver' }), 'iw:v3:demo': JSON.stringify({ S: { sid: 'd', ns: 'demo', stage: 'done', st: { name: 'MealMind' } }, view: 'ver' }), 'iw:v3:history': JSON.stringify([{ sid: 'old', name: 'MealMind', p: 63, o: 'INVEST WITH CONDITIONS', conf: { market: 40, customer: 40, money: 40, exec: 40, devil: 40 }, ts: 1 }]) });
const clean = (c) => { const h = c.$ev("$('#main').innerHTML"); assert.strictEqual(c.$ev('S'), null); assert.strictEqual(c.$ev('view'), 'dash'); assert(h.includes('INVESTOR WAR') && h.includes('TRY LIVE DEMO')); assert(!/INVESTMENT DECISION|63%|SIMULATION COMPLETE/.test(h)); assert(!bad.test(h) && !/MealMind|Market Shark|MARKET SHARK.*concern/.test(h.replace(/MARKET SHARK/g, ''))); for (const e of ['V.ver()', 'V.xray()', 'V.radar()', 'V.split()', 'V.evid()', 'V.lab()', 'V.amb()']) { const x = c.$ev(e); assert(!/INVESTMENT DECISION|63%/.test(x) && !bad.test(x) && !/MealMind/.test(x), e); } };
t('FRESH LAUNCH: empty storage, no cookies, no query => clean landing, nothing stale', () => { const c = boot(); clean(c); assert(c.$ev("$('#build').textContent").startsWith('build 2.2.1')); assert.strictEqual(c.$ev('BASE.conf.market'), 55); });
t('FRESH LAUNCH with poisoned storage (old completed 63% MealMind run) => still clean landing', () => { const c = boot({ store: poison() }); clean(c); assert(!c.store['iw_s'] && !c.store['iw:v3:active'], 'invalid/finished state purged'); assert(c.$ev('V.hist()').includes('MealMind'), 'history still shows the old attempt'); });
t('an unfinished user sim is restored but opens on the dashboard, never the war room/verdict', () => { const s = {}; const a = boot({ store: s }); user(a, 'market'); a.$ev('startWar()'); a.submitInput({ mode: 'text', text: GEN }); const sid = a.$ev('S.sid'); a.$ev("view='war';save()"); const b = boot({ store: s }); assert.strictEqual(b.$ev('S.sid'), sid); assert.strictEqual(b.$ev('view'), 'dash'); assert(!/INVESTMENT DECISION/.test(b.$ev("$('#main').innerHTML"))); });
t('verdict view renders nothing until a simulation reaches the verdict stage', () => { const c = boot(); assert(/No verdict yet/.test(c.$ev('V.ver()'))); user(c, 'market'); c.$ev('startWar()'); assert(/No verdict yet/.test(c.$ev('V.ver()'))); });
t('FRESH -> TRY LIVE DEMO -> completes; FRESH -> ENTER THE WAR -> user sim; no cross-contamination', () => {
  const dc = boot(); clean(dc); dc.$ev('newSim(DEMO,true)'); const DA = dc.$ev('DA'); dc.$ev('startWar()'); let g = 0; while (dc.$ev('S.stage') !== 'done' && g++ < 30) { const st = dc.$ev('S.stage'); dc.submitInput({ mode: 'text', text: st === 'ambush' ? DA.amb : st === 'boss' ? DA.boss : DA[dc.$ev('S.cur.inv')][Math.min(dc.$ev('S.asked[S.cur.inv]'), 2)] || DA.devil[0] }); } assert.strictEqual(dc.$ev('S.stage'), 'done'); const dsid = dc.$ev('S.sid'); assert.strictEqual(dc.$ev('S.ns'), 'demo'); assert(!dc.store['iw:v3:active'], 'demo never written as the active simulation');
  const uc = boot(); clean(uc); uc.$ev('startNew(null)'); assert.strictEqual(uc.$ev('S'), null); assert.strictEqual(uc.$ev('view'), 'pitch'); assert(uc.$ev("$('#main').innerHTML").includes('NEW STARTUP')); user(uc, null); const usid = uc.$ev('S.sid'); finishSim(uc); assert.notStrictEqual(usid, dsid); assert.strictEqual(uc.$ev('S.ns'), 'user'); assert(!uc.store['iw:v3:demo'], 'user run never written to the demo slot');
  const du = JSON.stringify(dc.$ev('S')), uu = JSON.stringify(uc.$ev('S')); assert(!/2999/.test(du) && !bad.test(uu), 'cross-contamination'); assert(dc.$ev('S.verdict.o') && uc.$ev('S.verdict.o'));
  const dh = dc.$ev('V.ver()') + dc.$ev('V.lab()'), uh = uc.$ev('V.ver()') + uc.$ev('V.lab()') + uc.$ev('V.xray()'); assert(!/2999/.test(dh)); assert(!bad.test(uh) && uh.includes('2999')); });
t('required files, no secrets, vercel config, syntax', () => { for (const f of ['index.html', 'app.js', 'styles.css', 'ai-client.js', 'api/ai.js', 'lib/ai-service.js', 'dev-server.js', 'package.json', 'README.md', 'vercel.json', '.env.example', '.gitignore']) assert(fs.existsSync(path.join(R, f)), f);
  const walk = (d) => fs.readdirSync(d, { withFileTypes: true }).flatMap((e) => (e.name === 'node_modules' || e.name === 'test') ? [] : e.isDirectory() ? walk(path.join(d, e.name)) : [path.join(d, e.name)]); for (const f of walk(R)) { const s = fs.readFileSync(f, 'utf8'); assert(!/sk-[A-Za-z0-9_-]{20,}|AIza[0-9A-Za-z_-]{20,}|LLM_API_KEY[ \t]*=[ \t]*[^\s#]+/.test(s.replace(/process\.env\.LLM_API_KEY/g, '')), 'secret in ' + f); }
  assert(!/LLM_API_KEY|api[_-]?key/i.test(rd('app.js') + rd('ai-client.js') + rd('index.html')), 'key referenced in browser code'); assert(!/localStorage[^;]*key/i.test(rd('ai-client.js')));
  const v = JSON.parse(rd('vercel.json')); assert(v.functions['api/ai.js'].maxDuration >= 20 && v.redirects.some((r) => r.source.startsWith('/lib/'))); assert(/^LLM_API_KEY=$/m.test(rd('.env.example')));
  for (const f of ['app.js', 'ai-client.js', 'api/ai.js', 'lib/ai-service.js', 'dev-server.js']) new vm.Script(rd(f), { filename: f }); const css = rd('styles.css'); assert(/max-width:800px/.test(css) && /overflow-x:hidden/.test(css)); });
(async () => { for (const [n, f] of q) { try { await f(); pass++; console.log('PASS', n); } catch (e) { fail++; console.log('FAIL', n, '\n   ', (e && e.message || e).toString().split('\n')[0]); } } console.log(`\n${pass} passed, ${fail} failed (MOCK tests; no real provider)`); process.exit(fail ? 1 : 0); })();
