"use strict";
/* ===== MODELS & CONSTANTS ===== */
const INV={market:{n:'MARKET SHARK'},customer:{n:'CUSTOMER SHARK'},money:{n:'MONEY SHARK'},exec:{n:'EXECUTION SHARK'},devil:{n:'THE DEVIL'}};
const KEYS=Object.keys(INV),CORE=['market','customer','money','exec'];
const AREA={market:'market and competition',customer:'customer validation',money:'pricing and unit economics',exec:'execution'};
const GR={verified:[14,'VERIFIED','Founder provided direct, checkable proof.'],strong:[10,'STRONG EVIDENCE','Specific numbers backed by real validation.'],plausible:[3,'PLAUSIBLE','Reasonable, but not yet proven.'],unsupported:[-6,'UNSUPPORTED','Claim made without evidence.'],weak:[-8,'WEAK','Vague, hedged or self-defeating answer.'],avoiding:[-14,'AVOIDING QUESTION','The question was dodged.'],contradicted:[-12,'CONTRADICTED','']};
const NAV=[['dash','Dashboard'],['war','War Room'],['xray','Assumption X-Ray'],['radar','Contradiction Radar'],['evid','Evidence Meter'],['amb','Competitor Ambush'],['split','Investor Split & Memory'],['ver','Final Verdict'],['lab','Validation Lab'],['hist','Pitch History']];
const MEM={price:'Pricing',afford:'Pricing',small:'Customers',big:'Customers',mkt:'Market',nocomp:'Competition',comp:'Competition',trac:'Traction & revenue',team:'Team'};
let S=null,view='dash',showForm=false,DT=null,V={};
const $=s=>document.querySelector(s),E=t=>String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,Math.round(v))),fmt=s=>String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');
const col=v=>v>=70?'var(--g)':v>=50?'var(--a)':'var(--r)',bar=v=>`<div class="bar" role="img" aria-label="${v} percent"><i style="width:${v}%;background:${col(v)}"></i></div>`;
const tag=g=>`<span class="tag ${g}">${GR[g][1]}</span>`;
const empty=(h,p)=>`<div class="card" style="text-align:center;padding:36px 14px"><h2>${h}</h2><p class="m">${p}</p><button class="btn" data-a="demo">TRY LIVE DEMO</button></div>`;
const H=()=>{try{return JSON.parse(localStorage.getItem('iw_h')||'[]')}catch(e){return[]}},setH=a=>{try{localStorage.setItem('iw_h',JSON.stringify(a.slice(-20)))}catch(e){}};
/* ===== ENGINE: claims, evidence, contradictions ===== */
const sents=t=>t.split(/(?<=[.!?])\s+/),snip=(t,re)=>(sents(t).find(s=>re.test(s))||t).slice(0,140).trim();
function extract(t){const L=t.toLowerCase(),o=[],add=(type,re)=>{if(re.test(L))o.push({type,q:snip(t,re),text:snip(t,re)})};let m;
 const re=/(₹|rs\.?|\$|inr)\s?([\d,]+(?:\.\d+)?)(k)?(\s?(?:\/|per\s)?\s?(?:month|mo|year|outlet))?/gi;
 while(m=re.exec(t)){if(/^\s*(crore|lakh|cr\b|billion|million)/i.test(t.slice(re.lastIndex)))continue;let v=+m[2].replace(/,/g,'')*(m[3]?1e3:1);if(/year/.test(m[4]||''))v/=12;o.push({type:'price',val:v,text:m[0].trim(),q:snip(t,/(₹|rs\.?|\$|inr)/i)})}
 add('afford',/afford|cheap|low[- ]cost|low price/);add('small',/\bsmall\b|independent|mom[- ]and[- ]pop|\bsmb\b/);add('big',/\bchains?\b|enterprise/);
 const nc=/no (real |direct )?(competitor|competition)|nobody else|no one else/;add('nocomp',nc);if(!nc.test(L))add('comp',/competitor|alternative|versus|\bvs\.?\b|rivals?/);
 add('trac',/paid|paying|revenue|mrr|pilot|interview|signed|\bloi\b|waitlist|\d+ (customers|users|restaurants|owners)/);add('team',/co-?founder|i built|we built|shipped|years (of|at)|ran ops|experience/);add('mkt',/crore|billion|\btam\b|market size|million/);return o}
function detect(nc){const out=[],P=t=>S.claims.filter(c=>c.type===t),k=(id,a,b,why,inv)=>{if(!S.con.some(c=>c.id===id)&&!out.some(c=>c.id===id))out.push({id,a,b,why,inv,res:false,asked:false})};
 for(const n of nc){
  if(n.type==='price'&&n.val>=2000)P('afford').forEach(a=>k('aff',a.q,n.q,'The pricing position may conflict with the stated differentiation (affordability).','money'));
  if(n.type==='big')P('small').forEach(a=>k('seg',a.q,n.q,'Selling to small operators and to chains needs different products, sales cycles and prices.','customer'));
  if(n.type==='comp')P('nocomp').forEach(a=>k('comp',a.q,n.q,'Claiming no competitors and then naming rivals suggests the market was not researched.','market'));
  if(n.type==='nocomp')P('comp').forEach(a=>k('comp',n.q,a.q,'Claiming no competitors while rivals exist suggests the market was not researched.','market'));}
 return out.slice(0,2)}
function grade(t,cl,con){const L=t.toLowerCase(),w=t.trim().split(/\s+/).length;
 if(w<4||/don'?t know|no idea|next question|skip|not sure|trust me/.test(L))return'avoiding';if(con.length)return'contradicted';
 const num=(t.match(/\d[\d,.]*/g)||[]).length,val=/(paid|paying|signed|invoice|revenue|mrr|loi|pilot|interview|survey|waitlist|retention|churn|shipped|launched|built|ran ops|years)/.test(L),hedge=(L.match(/\b(think|believe|probably|hope|maybe|should|might|assume|hopefully|guess)\b/g)||[]).length;
 const s=Math.min(num,3)*1.2+(val?2.2:0)+(w>25?.6:0)-hedge*1.6-(cl.some(c=>c.type==='nocomp')?3:0);
 return s>=5?'verified':s>=3.6?'strong':s>=2?'plausible':s>=-.5?'unsupported':'weak'}
const AS={price:['High','Customers will pay this price','Willingness-to-pay interviews'],afford:['Med','Price sensitivity drives buying','Compare close rates at two price points'],big:['High','Chains/enterprises will buy from an early-stage startup','Run 10 enterprise discovery calls'],small:['Med','Small operators have budget and urgency','Interview 20 small operators on budget'],nocomp:['High','Customers have no substitute today','Map 10 substitutes customers use now'],trac:['Med','Early traction predicts repeatable demand','Convert free pilots to paid'],mkt:['Med','The reachable market is large enough','Bottom-up count of reachable customers'],team:['Low','The team can ship at the pace required','Ship one milestone in 14 days']};
function assume(cl,g){cl.forEach(c=>{const a=AS[c.type];if(!a||S.ass.some(x=>x.type===c.type&&x.src===c.q))return;if(S.ass.filter(x=>x.type===c.type).length>1)return;
 const ok=g==='verified'||g==='strong';S.ass.push({type:c.type,src:c.q,customer:S.st.customer||'Unspecified',pricing:c.type==='price'?c.text:'—',text:c.type==='price'?`${S.st.customer||'Customers'} will pay ${c.text}`:a[1],ev:g,risk:ok?(a[0]==='High'?'Med':'Low'):a[0]==='Low'?'Med':'High',val:a[2]})})}
/* ===== ENGINE: probability, selection, questions ===== */
function calc(){const w={market:.2,customer:.22,money:.22,exec:.16,devil:.2};let p=0;KEYS.forEach(k=>p+=S.conf[k]*w[k]);p-=S.con.reduce((a,c)=>a+(c.res?2:5),0);return clamp(p+S.adj,3,97)}
const lastc=t=>S.claims.filter(c=>c.type===t).slice(-1)[0];
function pick(){const last=S.qs[S.qs.length-1],ld=last&&last.inv==='devil';
 if(S.con.some(c=>!c.asked&&!c.res)&&!ld)return'devil';const sc=k=>S.risk[k]-S.asked[k]*28,c=CORE.filter(k=>S.asked[k]<3).sort((a,b)=>sc(b)-sc(a));
 return(!c.length||(!ld&&sc('devil')>sc(c[0])))?'devil':c[0]}
function genQ(k){const st=S.st,l=S.asked[k],cu=st.customer||'your customers',pr=lastc('price'),p=pr?pr.text:'',nm=st.name,lw=S.answers[S.answers.length-1],bad=lw&&['unsupported','weak','avoiding'].includes(lw.g),n=S.qs.length+1;
 let why=`Highest unresolved risk: ${INV[k].n} (${S.risk[k]}).`+(lw?` Your last answer was ${GR[lw.g][1]}.`:' Opening probe from your intake.'),t;
 if(k==='devil'){const c=S.con.find(c=>!c.asked&&!c.res);
  if(c){c.asked=true;return{n,inv:k,cid:c.id,text:`Earlier you said “${c.a}”. Now you say “${c.b}”. Which one is true, and what breaks if it is the other?`,why:'Contradiction Radar fired: your latest claim conflicts with an earlier one.'}}
  const w=[...S.answers].reverse().find(a=>['unsupported','weak'].includes(a.g));
  t=(l===0||!w)?`Assume it is 12 months from now and ${nm} is dead. What killed it?`:`You claimed “${(w.cl[0]?w.cl[0].q:w.a).slice(0,100)}”. Prove it or drop it.`}
 else{const L={market:[`How big is the market for ${nm}? Count the ${cu} you can actually reach and show how you got the number.`,`Who else solves this problem today, including doing nothing? Name them and tell me why a customer picks you.`,`If a bigger player copies this in one quarter, what do you still own?`],
  customer:[`Which ${cu} have you actually spoken to, and what did they DO, not say, about this problem?`,`How many of them are paying today, and how did you acquire each one?`,`What happened to those customers after 60 days: who stayed, who churned, why?`],
  money:[p?`You say ${p}. How many customers have agreed to pay that, and how many already have?`:`You never stated a price. What do you charge, and what evidence says customers will pay it?`,`What is your CAC and payback period${p?' at '+p:''}?`,`What is gross margin per customer after support, cloud and onboarding costs?`],
  exec:[`Why are you the team to build this? What have you already shipped?`,`What breaks first when you go from 10 customers to 100?`,`What is your biggest technical risk, and how do you retire it in 30 days?`]};
  t=(bad&&lw.inv===k?'That did not land. ':'')+L[k][Math.min(l,2)]}
 return{n,inv:k,text:t,why}}
function nextQ(){S.cur=genQ(pick());S.qs.push(S.cur);render()}
const DR={money:'Pricing',customer:'Customer',market:'Market',exec:'Execution',devil:'Devil'};
function submit(text,ov){if(!S||S.stage!=='war'||!S.cur)return;text=text.trim().slice(0,1200);const q=S.cur,cl=extract(text),con=detect(cl),g=(ov&&GR[ov.grade])?ov.grade:grade(text,cl,con),ow=S.prob,oc=S.conf[q.inv];
 if(ov)ovApply(ov,cl,con,q,text);
 if(q.cid){const c=S.con.find(x=>x.id===q.cid);if(c)c.res=g!=='avoiding'&&g!=='weak'}
 cl.forEach(c=>S.claims.push({...c,src:'Q'+q.n}));con.forEach(c=>S.con.push(c));
 const d=GR[g][0];S.conf[q.inv]=clamp(S.conf[q.inv]+d);if(q.inv!=='devil')S.conf.devil=clamp(S.conf.devil+d*.5);
 if(con.length){S.conf.devil=clamp(S.conf.devil-5);S.conf[con[0].inv]=clamp(S.conf[con[0].inv]-7)}
 S.ev[g]++;S.words[q.inv]+=text.split(/\s+/).length;S.asked[q.inv]++;S.risk[q.inv]=clamp(S.risk[q.inv]-d*1.3);S.risk.devil=clamp(S.risk.devil+con.length*18+(d<0?6:0));
 S.prob=calc();const why=(ov&&ov.reason)||(g==='contradicted'&&con[0]?con[0].why:GR[g][2]);S.why[q.inv]=why;
 S.log.unshift({inv:q.inv,g,dp:S.prob-ow,txt:`${INV[q.inv].n} confidence ${oc} → ${S.conf[q.inv]}. Probability ${ow}% → ${S.prob}%. ${why}`});
 S.answers.push({q:q.text,a:text,inv:q.inv,g,cl});assume(cl,g);S.cur=null;
 if(S.answers.length===4&&!S.ambush)toStage('ambush');else if(S.answers.length>=8||S.left<=0)toStage('boss');else nextQ()}
function toStage(st){S.stage=st;if(st==='ambush'||st==='boss'){S.sd=Date.now()+60000;S.sl=60}render()}
function resumeWar(){S.stage='war';S.dl=Date.now()+S.left*1000;nextQ()}
function evalAmb(t){const L=t.toLowerCase(),w=t.split(/\s+/).length,f=[['Differentiation',/unique|integrat|proprietary|data|only/],['Defensibility',/switch|lock|contract|moat|integrat|data/],['Customer loyalty',/renew|retention|loyal|relationship|support|churn/],['Strategy',/niche|focus|segment|ignore|premium|partner/],['Execution',/ship|weekly|speed|team|roadmap|fast/]],r=f.map(([n,re])=>[n,re.test(L)]);
 const s=clamp(15+r.filter(x=>x[1]).length*17-(w<15?20:0));return{score:s,rows:r,note:s>=60?'Founder showed defensible positioning.':'Response did not show why customers would stay.'}}
function evalBoss(t){const L=t.toLowerCase(),w=t.split(/\s+/).length,h=r=>r.test(L)?1:0,n=(t.match(/\d[\d,.]*/g)||[]).length,hd=(L.match(/\b(think|maybe|hope|probably|might)\b/g)||[]).length;
 const ob=['pric','competit|moat|switch','churn|retention|renew','cac|acqui','chain|segment|small','team|built'].filter(x=>new RegExp(x).test(L)).length;
 const c={'Clarity':w>=35&&w<=170?85:w>=20?60:30,'Evidence':25+n*12+h(/interview|pilot|paid|paying|signed/)*20,'Confidence':80-hd*18,'Differentiation':30+h(/integrat|proprietary|data|moat|switch/)*40+h(/unique|only|first/)*10,'Business model':30+h(/₹|\$|rs/)*20+h(/month|mrr|margin|cac|payback/)*30,'Traction':25+h(/paid|paying|revenue|pilots/)*30+Math.min(n,3)*8,'Persuasiveness':35+Math.min(w,80)/2+h(/raising|ask|invest/)*12,'Addresses objections':25+ob*15};
 Object.keys(c).forEach(k=>c[k]=clamp(c[k],10,100));return{c,avg:clamp(Object.values(c).reduce((a,b)=>a+b,0)/8)}}
function subSubmit(){if(!S||(S.stage!=='ambush'&&S.stage!=='boss'))return;S.sd=Infinity;const t=(($('#ans')||{}).value||'').trim().slice(0,1500),ow=S.prob;
 if(S.stage==='ambush'){const r=(S.ovJ&&S.ovJ.kind==='ambush'&&S.ovJ.r)||evalAmb(t);S.ambush={text:t,...r};S.adj+=Math.round((r.score-50)/5);S.prob=calc();S.log.unshift({inv:'devil',g:r.score>=60?'strong':'weak',dp:S.prob-ow,txt:`Ambush response scored ${r.score}/100. Probability ${ow}% → ${S.prob}%. ${r.note}`});resumeWar()}
 else{const r=(S.ovJ&&S.ovJ.kind==='boss'&&S.ovJ.r)||evalBoss(t);S.boss={text:t,...r};S.adj+=Math.round((r.avg-55)/4);S.prob=calc();S.log.unshift({inv:'devil',g:r.avg>=60?'strong':'weak',dp:S.prob-ow,txt:`Final Boss scored ${r.avg}/100. Probability ${ow}% → ${S.prob}%.`});finish()}}
function finish(){S.stage='done';const c=S.conf,ev=S.ev,n=Object.values(ev).reduce((a,b)=>a+b,0)||1,p=S.prob;
 const evs=clamp((ev.verified*100+ev.strong*80+ev.plausible*55+ev.unsupported*30+ev.weak*12+ev.contradicted*5)/n);
 const dim={'Market potential':c.market,'Customer validation':c.customer,'Business model':c.money,'Execution':c.exec,'Defensibility':clamp((S.ambush?S.ambush.score:40)*.6+c.market*.4),'Evidence strength':evs,'Founder readiness':S.boss?S.boss.avg:40};
 const s=[...CORE].sort((a,b)=>c[b]-c[a]),lo=s[3],hi=CORE.slice().sort((a,b)=>S.words[b]-S.words[a])[0];
 S.verdict={p,o:p>=72?'INVEST':p>=58?'INVEST WITH CONDITIONS':p>=42?'INTERESTED — PROVE IT':'PASS',dim,adv:s[0],flag:lo,
  bs:lo!==hi?`You spent the most words on ${AREA[hi]}, but the panel's biggest concern is ${AREA[lo]} (${INV[lo].n} at ${c[lo]}%).`:`You defended ${AREA[lo]} hardest, yet it is still the weakest area (${c[lo]}%). More words will not fix it; evidence will.`};
 const h=H();h.push({ts:Date.now(),name:S.st.name,p,o:S.verdict.o,conf:{...c},demo:S.demo,pv:rewrite(),orig:S.st.pitch});setH(h);view='ver';render()}
/* ===== SESSION ===== */
function newSim(st,demo){clearTimeout(DT);const cl=extract([st.pitch,st.customer?`Customers: ${st.customer}.`:'',st.price?`Price: ${st.price}.`:'',st.trac||''].join(' '));
 S={st,demo,claims:cl.map(c=>({...c,src:'Intake'})),qs:[],answers:[],cur:null,conf:{market:55,customer:55,money:55,exec:55,devil:45},ev:{verified:0,strong:0,plausible:0,unsupported:0,weak:0,avoiding:0,contradicted:0},risk:{market:55,customer:60,money:65,exec:50,devil:30},asked:{market:0,customer:0,money:0,exec:0,devil:0},words:{market:0,customer:0,money:0,exec:0,devil:0},why:{},ass:[],con:[],log:[],adj:0,stage:'scan',left:600,dl:0,sd:Infinity,sl:60,ambush:null,boss:null,verdict:null};
 const has=t=>cl.some(c=>c.type===t);if(!has('price')){S.risk.money+=15;S.conf.money-=6}if(!has('trac')){S.risk.customer+=12;S.conf.customer-=6}if(!has('team'))S.risk.exec+=6;if(!has('mkt'))S.risk.market+=5;
 assume(cl,'plausible');S.prob=calc();view='war';showForm=false;render();if(demo)DT=setTimeout(startWar,4200)}
function startWar(){if(!S||S.stage!=='scan')return;S.stage='war';S.dl=Date.now()+600000;S.left=600;nextQ()}
const DEMO={name:'MealMind',pitch:'An affordable AI that tells restaurants how much to cook each day, cutting food waste by 30%.',customer:'small independent restaurants',price:'₹999 per month',trac:''};
const DA={money:['We charge ₹999 per month. I think most restaurants will probably pay it.','Only 3 of the 12 owners pay today, ₹999 per month each. The rest asked for a free trial first.','CAC is about ₹2,400 from WhatsApp outreach; at ₹999 per month payback is under 3 months and gross margin is 71%.'],
customer:['We interviewed 12 small restaurant owners in Chennai; 3 run paid pilots for 6 weeks and cut waste by 22%.','3 of 12 pay today. We found them through two owner WhatsApp groups and 40 cold visits.','Two of the 3 pilots renewed after 60 days and none churned; one asked for a second outlet.'],
market:['Our real target is restaurant chains and enterprise kitchens at ₹4,999 per month per outlet, a ₹2,000 crore market.','Honestly, there are no real competitors in this space today.','Our competitors are Wasteless and Leanpath, but we integrate with POS systems and hold 6 weeks of live demand data per outlet.'],
exec:['I built the forecasting model myself and my cofounder ran ops at a 40-outlet chain for 6 years. We ship every week.','Onboarding breaks first: it takes 4 days per outlet today, so we are automating POS import to make it under 1 hour.','Forecast accuracy is the risk: we hit 88% on 6 weeks of data and will validate on 3 more outlets in 30 days.'],
devil:['I mixed segments. We start with small independent restaurants at ₹999 per month and sell chains only after 20 paid customers.','The ₹999 plan is for small kitchens; chains pay more because they need integrations. We will not claim both advantages.','Fair point. We are not the only player; our edge is POS integration and live data, not the absence of competition.'],
amb:'Free copies of our feature will not hurt much: we are integrated into each restaurant POS and hold their live data, so switching costs are high. Our 3 paying pilots renewed. We ship weekly and focus on small kitchens that competitors ignore, with local WhatsApp support.',
boss:'MealMind cuts restaurant food waste by predicting daily demand. We interviewed 12 owners, 3 pay ₹999 per month today and cut waste 22%. We start with small independent restaurants and add chains only after 20 paid customers. Our moat is POS integration and live demand data, not low price. CAC is ₹2,400 with under 3-month payback and 71% margin. We are raising ₹50 lakh to reach 25 paying restaurants in 90 days.'};
function demoPlay(){clearTimeout(DT);if(!S||!S.demo||view!=='war'||!$('#ans'))return;let txt;
 if(S.stage==='war'&&S.cur)txt=DA[S.cur.inv][Math.min(S.asked[S.cur.inv],2)];else if(S.stage==='ambush')txt=DA.amb;else if(S.stage==='boss')txt=DA.boss;else return;let i=0;
 DT=setTimeout(function f(){const a=$('#ans');if(!S||!S.demo||!a)return;i+=2;a.value=txt.slice(0,i);if(i<txt.length)DT=setTimeout(f,22);else DT=setTimeout(()=>{if(S&&S.demo)S.stage==='war'?submit(a.value):subSubmit()},1200)},2600)}
setInterval(()=>{const n=Date.now();if(S){if(S.stage==='war'&&S.dl&&!S.frozen){S.left=Math.max(0,Math.ceil((S.dl-n)/1000));if(S.left<=0&&S.cur){S.cur=null;S.msg='Time expired. The committee moves to the Final Boss.';toStage('boss')}}
 if((S.stage==='ambush'||S.stage==='boss')&&isFinite(S.sd)){S.sl=Math.max(0,Math.ceil((S.sd-n)/1000));if(S.sl<=0)subSubmit()}}
 const c=$('#clk'),p=$('#prob'),s=$('#sub');if(c)c.textContent=fmt(S?S.left:600);if(p)p.textContent=S?S.prob+'%':'--';if(s&&S)s.textContent=fmt(S.sl)},250);
/* ===== VIEWS ===== */
const chip=k=>`<div><b>${INV[k].n}</b> <span class="mono" style="float:right;color:${col(S.conf[k])}">${S.conf[k]}%</span>${bar(S.conf[k])}</div>`;
const formH=()=>`<div class="card"><h3>NEW STARTUP</h3><label for="f1">Startup name</label><input id="f1" maxlength="60"><label for="f2">One-sentence pitch (required)</label><textarea id="f2" rows="2" maxlength="300"></textarea><label for="f3">Target customer (blank = I don't know yet)</label><input id="f3" maxlength="100"><label for="f4">Price, e.g. ₹999 per month (blank = I don't know yet)</label><input id="f4" maxlength="60"><label for="f5">Traction so far (blank = none yet)</label><input id="f5" maxlength="200"><p id="err" role="alert" style="color:var(--r)"></p><button class="btn" data-a="begin">START PRE-WAR SCAN</button></div>`;
V.dash=()=>`<div class="card"><div class="mono" style="color:var(--c)">STARTUP INVESTMENT COMMITTEE</div><h1 style="font-size:clamp(30px,7vw,56px);margin:6px 0">INVESTOR WAR</h1><h2 style="color:var(--r);font-size:clamp(14px,3.2vw,20px)">YOUR STARTUP HAS 10 MINUTES TO SURVIVE.</h2><p class="m">Five AI investors. Zero politeness. One investment decision.</p><div class="row"><button class="btn" data-a="demo">TRY LIVE DEMO</button><button class="btn alt" data-a="form">PITCH YOUR STARTUP</button></div></div>${showForm?formH():''}
${S?`<div class="card"><h3>${E(S.st.name)}</h3><p class="m">Stage: ${S.stage} · ${S.answers.length} answers · ${S.con.length} contradictions · probability ${S.prob}%</p><button class="btn alt" data-v="war">${S.stage==='done'?'VIEW RESULT':'RESUME WAR ROOM'}</button></div>`:''}
<div class="card"><h3>HOW IT WORKS</h3><p class="m">Every answer is parsed into claims, graded for evidence, checked against earlier claims, and used to pick the next investor by strongest unresolved risk. This build runs a deterministic local engine, so it needs no API key.</p></div>`;
function scanH(){const top=CORE.slice().sort((a,b)=>S.risk[b]-S.risk[a])[0];return`<div class="card amb"><h2>PRE-WAR SCAN</h2><p class="m">Intake parsed. The committee found ${S.claims.length} claims and ${S.ass.length} hidden assumptions.</p><div class="g">${KEYS.map(chip).join('')}</div><p>Largest opening risk: <b>${INV[top].n}</b> (${S.risk[top]}). ${!S.claims.some(c=>c.type==='price')?'No price was given.':''} ${!S.claims.some(c=>c.type==='trac')?'No traction was given.':''}</p><ul>${S.claims.map(c=>`<li>${E(c.q)}</li>`).join('')}</ul><button class="btn" data-a="start">ENTER THE WAR ROOM</button></div>`}
const subH=(t,lead,body)=>`<div class="card ${t==='ambush'?'amb':'red'}"><h2>${lead}</h2><p class="q">${body}</p><p>TIME LEFT <b class="big mono" id="sub">${fmt(S.sl)}</b></p><label for="ans">Your response</label><textarea id="ans" rows="5" maxlength="1500"></textarea><div class="row"><button class="btn" data-a="sub">SUBMIT RESPONSE</button>${S.demo?'<button class="btn alt" data-a="take">TAKE OVER</button>':''}</div></div>`;
V.war=()=>{if(!S)return empty('No simulation yet','Watch MealMind face the committee, or pitch your own startup from the Dashboard.');if(S.stage==='scan')return scanH();
 let h=`<div class="card"><div class="g">${KEYS.map(chip).join('')}</div></div>`;
 if(S.msg)h+=`<div class="card red">${E(S.msg)}</div>`;
 if(S.thinking)h+=`<div class="card"><h2>THE COMMITTEE IS THINKING</h2><p class="m" role="status">${E(S.thinking)}</p></div>`;
 else if(S.stage==='ambush')h+=subH('ambush','COMPETITOR AMBUSH',S.ambTxt?E(S.ambTxt):'YOUR BIGGEST COMPETITOR LAUNCHES YOUR CORE FEATURE TOMORROW AND OFFERS IT FOR FREE. You have 60 seconds.');
 else if(S.stage==='boss')h+=subH('boss','FINAL BOSS','You have 60 seconds. Convince the panel to invest and answer every objection raised so far.');
 else if(S.stage==='done')h+=`<div class="card"><h2>SIMULATION COMPLETE</h2><button class="btn" data-v="ver">SEE FINAL VERDICT</button></div>`;
 else if(S.cur)h+=`<div class="card"><span class="tag plausible">${INV[S.cur.inv].n}</span> <span class="m">Question ${S.cur.n}</span><p class="q">${E(S.cur.text)}</p><p class="why">WHY THIS QUESTION: ${E(S.cur.why)}</p><label for="ans">Your answer (Ctrl+Enter to send)</label><textarea id="ans" rows="4" maxlength="1200"></textarea><div class="row"><button class="btn" data-a="send">ANSWER</button><button class="btn alt" data-a="freeze">${S.frozen?'RESUME CLOCK':'FREEZE CLOCK'}</button>${S.demo?'<button class="btn alt" data-a="take">TAKE OVER</button>':''}</div></div>`;
 return h+`<div class="card"><h3>SCORE CHANGES</h3>${S.log.length?S.log.slice(0,5).map(l=>`<div class="log">${tag(l.g)} <b style="color:${l.dp>=0?'var(--g)':'var(--r)'}">${l.dp>=0?'+':''}${l.dp}</b> ${E(l.txt)}</div>`).join(''):'<p class="m">No answers yet.</p>'}</div>`};
V.xray=()=>!S?empty('No assumptions yet','Run a simulation to expose hidden assumptions.'):S.ass.length?S.ass.map(a=>`<div class="card"><div class="g"><div><span class="m">CUSTOMER</span><br>${E(a.customer)}</div><div><span class="m">PRICING</span><br>${E(a.pricing)}</div><div><span class="m">EVIDENCE</span><br>${tag(a.ev)}</div><div><span class="m">RISK</span><br><b style="color:${a.risk==='High'?'var(--r)':a.risk==='Med'?'var(--a)':'var(--g)'}">${a.risk.toUpperCase()}</b></div></div><p><b>ASSUMPTION</b> ${E(a.text)}</p><p class="m">Validation: ${E(a.val)}</p></div>`).join(''):empty('No assumptions extracted','Answer questions to expose them.');
V.radar=()=>!S?empty('Radar offline','Run a simulation to scan for contradictions.'):S.con.length?S.con.map(c=>`<div class="card red"><h3 style="color:var(--r)">CONTRADICTION DETECTED</h3><p class="m">EARLIER CLAIM</p><p>“${E(c.a)}”</p><p class="m">CURRENT CLAIM</p><p>“${E(c.b)}”</p><p><b>WHY IT MATTERS</b> ${E(c.why)}</p><p>${c.res?'<span class="tag strong">ADDRESSED BY FOUNDER</span>':c.asked?'<span class="tag unsupported">DEVIL IS WAITING</span>':'<span class="tag weak">QUEUED FOR THE DEVIL</span>'}</p></div>`).join(''):`<div class="card"><h3>NO CONTRADICTIONS YET</h3><p class="m">${S.claims.length} claims are on file and every new answer is compared against them.</p></div>`;
V.evid=()=>{if(!S)return empty('No evidence yet','Run a simulation to build the evidence meter.');const n=S.answers.length||1;
 return`<div class="card"><h3>EVIDENCE METER</h3>${Object.keys(GR).map(g=>`<p>${tag(g)} <b class="mono">${S.ev[g]}</b>${bar(Math.round(S.ev[g]/n*100))}</p>`).join('')}</div>${S.answers.map(a=>`<div class="card">${tag(a.g)} <span class="m">${INV[a.inv].n}</span><p class="m">${E(a.q)}</p><p>${E(a.a)}</p></div>`).join('')}`};
V.amb=()=>!S||!S.ambush?empty('No ambush yet','The ambush fires after the fourth answer.'):`<div class="card amb"><h3>COMPETITOR AMBUSH RESULT</h3><p>${E(S.ambush.text||'(no response)')}</p><p class="big mono" style="color:${col(S.ambush.score)}">${S.ambush.score}/100</p>${S.ambush.rows.map(r=>`<p>${r[1]?'✔':'✘'} ${r[0]}</p>`).join('')}<p class="m">${S.ambush.note}</p></div>`;
V.split=()=>{if(!S)return empty('No panel yet','Run a simulation to see the investors split.');const s=KEYS.slice().sort((a,b)=>S.conf[b]-S.conf[a]),hi=s[0],lo=s[4],g={};S.claims.forEach(c=>{(g[MEM[c.type]]=g[MEM[c.type]]||[]).push(c)});
 return`<div class="card"><h3>BIGGEST DISAGREEMENT</h3><p>${INV[hi].n} <b style="color:var(--g)">${S.conf[hi]}%</b> vs ${INV[lo].n} <b style="color:var(--r)">${S.conf[lo]}%</b></p><p class="m">${INV[hi].n}: ${E(S.why[hi]||'No answers on this topic yet.')}<br>${INV[lo].n}: ${E(S.why[lo]||'No answers on this topic yet.')}</p></div><div class="card"><div class="g">${KEYS.map(chip).join('')}</div></div><div class="card"><h3>INVESTOR MEMORY</h3>${Object.keys(g).map(k=>`<p><b>${k}</b></p><ul>${g[k].slice(0,4).map(c=>`<li>${E(c.q)} <span class="m">(${c.src})</span></li>`).join('')}</ul>`).join('')||'<p class="m">Nothing remembered yet.</p>'}</div>`};
V.ver=()=>{if(!S||!S.verdict)return empty('No verdict yet','Finish the Final Boss to receive a decision.');const v=S.verdict,un=S.answers.filter(a=>['unsupported','weak'].includes(a.g));
 return`<div class="card ${v.p>=58?'':'red'}"><div class="m">INVESTMENT DECISION</div><h1 style="color:${col(v.p)}">${v.o}</h1><p class="big mono">${v.p}% probability</p></div><div class="card"><div class="g">${Object.entries(v.dim).map(([k,x])=>`<div><b>${k}</b> <span class="mono" style="float:right">${x}</span>${bar(x)}</div>`).join('')}</div></div>
 <div class="g"><div class="card"><h3>STRONGEST ADVANTAGE</h3><p>${INV[v.adv].n} at ${S.conf[v.adv]}%</p><h3>BIGGEST RED FLAG</h3><p>${INV[v.flag].n} at ${S.conf[v.flag]}%: ${E(S.why[v.flag]||'')}</p></div><div class="card"><h3>FOUNDER BLIND SPOT</h3><p>${E(v.bs)}</p></div></div>
 <div class="card"><h3>HIDDEN ASSUMPTIONS</h3><ul>${S.ass.filter(a=>a.risk==='High').map(a=>`<li>${E(a.text)}</li>`).join('')||'<li>None rated high risk.</li>'}</ul><h3>CONTRADICTIONS</h3><ul>${S.con.map(c=>`<li>${E(c.why)}</li>`).join('')||'<li>None detected.</li>'}</ul><h3>UNSUPPORTED CLAIMS</h3><ul>${un.map(a=>`<li>${E((a.cl[0]?a.cl[0].q:a.a).slice(0,120))}</li>`).join('')||'<li>None.</li>'}</ul><h3>EVIDENCE NEEDED</h3><ul>${exps().slice(0,3).map(e=>`<li>${E(e[5])}</li>`).join('')}</ul></div>
 ${S.boss?`<div class="card"><h3>FINAL BOSS SCORE ${S.boss.avg}/100</h3><div class="g">${Object.entries(S.boss.c).map(([k,x])=>`<div>${k} <b class="mono" style="float:right">${x}</b>${bar(x)}</div>`).join('')}</div></div>`:''}
 ${aiNotes()}<div class="row"><button class="btn" data-v="lab">VALIDATION LAB</button><button class="btn alt" data-v="hist">PITCH HISTORY</button></div>`};
const X={price:['Interview 30 {c} and ask each to prepay {p}','At least 40% commit to pay','5 days','₹2,000','Willingness-to-pay rate'],afford:['Quote two price points to 20 prospects each','Close-rate gap under 10 points','5 days','₹1,000','Close rate by price'],big:['Hold 10 discovery calls with chain buyers','3 agree to a paid pilot','10 days','₹3,000','Pilot agreement rate'],small:['Interview 20 small operators about budget','12 say they would pay','4 days','₹1,500','Budget confirmation rate'],nocomp:['Ask 15 buyers what they use today and list substitutes','Top 3 substitutes and switching reasons documented','3 days','₹500','Substitutes per buyer'],trac:['Convert 3 free pilots to paid within 14 days','2 of 3 pay','14 days','₹0','Pilot-to-paid conversion'],mkt:['Build a bottom-up count of reachable customers','Reachable base supports ₹10 crore revenue','2 days','₹0','Reachable customer count'],team:['Ship one customer-visible milestone','Shipped and used by 3 customers','14 days','₹0','Milestones shipped']};
function exps(){if(S.aiExps&&S.aiExps.length)return S.aiExps.map(e=>[e.hypothesis,e.experiment+' (Target customer: '+e.target+')',e.success,e.time,e.cost,'',e.metric]);
 const c=S.st.customer||'target customers',seen={},o=[];S.ass.slice().sort((a,b)=>(b.risk==='High')-(a.risk==='High')).forEach(a=>{if(seen[a.type]||!X[a.type]||o.length>=4)return;seen[a.type]=1;const x=X[a.type];o.push([a.text,x[0].replace('{c}',c).replace('{p}',a.pricing),x[1],x[2],x[3],x[4]])});
 o.push(['Acquisition cost is sustainable','Spend ₹5,000 on one channel and count paid signups','CAC under 3 months of revenue','7 days','₹5,000','Cost per paid customer']);return o.map(e=>[e[0],e[1],e[2],e[3],e[4],e[1]+' ('+e[5]+')',e[5]]).map(e=>{e[5]=e[1];return e})}
function rewrite(){if(S.aiRw)return S.aiRw;
 const st=S.st,g=S.answers.filter(a=>['verified','strong'].includes(a.g)).map(a=>sents(a.a)[0]),pr=lastc('price'),dif=S.ambush&&S.ambush.text?sents(S.ambush.text)[0]:'[ADD: why customers stay if a rival goes free]';
 return[['Problem',st.pitch],['Customer',st.customer||'[ADD: exactly who pays]'],['Evidence',g.slice(0,2).join(' ')||'[ADD: interviews, pilots or payments]'],['Solution',st.pitch],['Differentiation',dif],['Business model',pr?`${pr.text}. [ADD: CAC and margin]`:'[ADD: price and margin]'],['Traction',S.claims.filter(c=>c.type==='trac').slice(-2).map(c=>c.q).join(' ')||'[ADD: traction]'],['Ask','[ADD: raise amount and the milestone it buys]']]}
V.lab=()=>{if(!S||!S.verdict)return empty('Lab is empty','Finish a simulation to get experiments, a rewritten pitch and a 7-day plan.');const cn=S.con[0],plan=[['Day 1',cn?`Resolve the contradiction: choose one story between “${cn.a.slice(0,50)}” and “${cn.b.slice(0,50)}”.`:'Write down your three riskiest assumptions.'],['Day 2','Book 15 customer interviews.'],['Day 3','Run interviews and log willingness to pay.'],['Day 4','Ask 10 prospects to prepay or sign a paid pilot.'],['Day 5','Competitor teardown: 5 alternatives and why customers switch.'],['Day 6','Test one acquisition channel with ₹5,000 and measure CAC.'],['Day 7','Rewrite the pitch with the new evidence and re-run INVESTOR WAR.']];
 return`<h2>VALIDATION LAB</h2>${exps().map(e=>`<div class="card"><p><b>ASSUMPTION</b> ${E(e[0])}</p><p><b>EXPERIMENT</b> ${E(e[1])}</p><p><b>SUCCESS CRITERIA</b> ${E(e[2])}</p><p class="m">TIME ${e[3]} · COST ${e[4]} · METRIC ${E(e[6])}</p></div>`).join('')}
 <h2>PITCH REWRITER</h2><div class="g"><div class="card"><h3>ORIGINAL PITCH</h3><p>${E(S.st.pitch)}</p></div><div class="card"><h3>INVESTOR-READY PITCH</h3>${rewrite().map(r=>`<p><b>${r[0]}</b><br>${E(r[1])}</p>`).join('')}</div></div>
 <h2>7-DAY FOUNDER PLAN</h2><div class="card"><table>${plan.map(p=>`<tr><th>${p[0]}</th><td>${E(p[1])}</td></tr>`).join('')}</table></div>`};
V.hist=()=>{const h=H();if(!h.length)return empty('No attempts saved','Each finished simulation is saved on this device.');
 return`<div class="card"><h3>IMPROVEMENT ACROSS ATTEMPTS</h3>${h.map((x,i)=>{const pv=h[i-1],d=pv?CORE.map(k=>[k,x.conf[k]-pv.conf[k]]).filter(a=>a[1]).sort((a,b)=>Math.abs(b[1])-Math.abs(a[1])).slice(0,2).map(a=>`${DR[a[0]]} ${a[1]>0?'+':''}${a[1]}`).join(', '):'baseline';return`<div class="it"><b>Attempt ${i+1}</b> · ${E(x.name)} · ${x.o} <b class="mono" style="float:right">${x.p}%</b>${bar(x.p)}<span class="m">${pv?(x.p-pv.p>=0?'+':'')+(x.p-pv.p)+' points. Changed: '+(d||'no change'):d} · ${new Date(x.ts).toLocaleString()}</span>${x.pv?`<details><summary>VIEW PITCH VERSION</summary><p class="m">ORIGINAL: ${E(x.orig||'')}</p>${x.pv.map(r=>`<p><b>${r[0]}</b><br>${E(r[1])}</p>`).join('')}</details>`:''}</div>`}).join('')}<button class="btn alt" data-a="clr">CLEAR HISTORY</button></div>`};
/* ===== RENDER & EVENTS ===== */
V.amb2=V.amb;
function aiNotes(){return''}
function ovApply(){}
const save=()=>{try{if(S)localStorage.setItem('iw_s',JSON.stringify({S,view}));else localStorage.removeItem('iw_s')}catch(e){}};
function restore(){try{const r=JSON.parse(localStorage.getItem('iw_s')||'null');if(!r||!r.S||!r.S.st)return;S=r.S;view=r.view||'dash';S.demo=false;S.thinking=false;S.ovJ=null;const n=Date.now();if(S.stage==='war'){S.frozen=false;S.dl=n+(S.left||0)*1000}else if(S.stage==='ambush'||S.stage==='boss')S.sd=n+(S.sl||60)*1000}catch(e){S=null}}
function render(){$('#nav').innerHTML=NAV.map(([k,n])=>`<button data-v="${k}" class="${k===view?'on':''}" ${k===view?'aria-current="page"':''}>${n}</button>`).join('');
 let h;try{h=(V[view]||V.dash)()}catch(e){console.error(e);h=empty('Something went wrong','Restart the simulation.')}$('#main').innerHTML=h;save();demoPlay()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-v],[data-a]');if(!b)return;const a=b.dataset.a;if(b.dataset.v){view=b.dataset.v;render();return}
 if(a==='demo')newSim(DEMO,true);else if(a==='form'){showForm=true;view='dash';render()}
 else if(a==='begin'){const v=i=>($('#f'+i).value||'').trim();if(v(2).length<10){$('#err').textContent='Describe your startup in at least 10 characters.';return}let pr=v(4);if(/\d/.test(pr)&&!/[₹$]|rs|inr/i.test(pr))pr='₹'+pr;newSim({name:v(1)||'Your startup',pitch:v(2),customer:v(3),price:pr,trac:v(5)},false)}
 else if(a==='start')startWar();else if(a==='send'){const t=$('#ans').value;if(t.trim().length<2){return}submit(t)}else if(a==='sub')subSubmit();
 else if(a==='take'){S.demo=false;clearTimeout(DT);render()}
 else if(a==='freeze'){S.frozen=!S.frozen;if(!S.frozen)S.dl=Date.now()+S.left*1000;render()}
 else if(a==='restart'){clearTimeout(DT);S=null;view='dash';showForm=false;render()}
 else if(a==='clr'){setH([]);render()}});
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)&&e.target.id==='ans'){S&&S.stage==='war'?submit(e.target.value):subSubmit()}});
restore();render();
